id = links
name = Links
mainURL = https://nikoboi.dev/links
icon = clippy.png

allowSubdomains = true
requireDoubleBackToExit = false

enableExternalLinks = true
openExternalLinksInBrowser = true
confirmOpenInBrowser = false

allowOpenMobileApp = true
deeplink = nikoboi.dev

